# Generated by Django 6.0.3 on 2026-09-18 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active_doctor_receptionist'),
        ('medical_records', '0002_prescription_prescriptionmedicine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('LAB_REPORT', 'Lab Report'), ('SCAN_REPORT', 'Scan / Imaging Report'), ('PRESCRIPTION', 'Prescription'), ('DISCHARGE_SUMMARY', 'Discharge Summary'), ('REFERRAL', 'Referral'), ('OTHER', 'Other Medical Document')], default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='medical_files/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_medical_files', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_files', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_medical_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-document_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'file_type'], name='medical_rec_patient_0986b7_idx'), models.Index(fields=['patient', 'created_at'], name='medical_rec_patient_c25b45_idx')],
            },
        ),
    ]
