# Generated by Django 6.0.3 on 2026-09-15 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, db_index=True, max_length=30)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20)),
                ('module', models.CharField(db_index=True, max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['role', 'created_at'], name='audit_logs__role_e3f7bd_idx'), models.Index(fields=['module', 'created_at'], name='audit_logs__module_865b40_idx'), models.Index(fields=['action', 'created_at'], name='audit_logs__action_70fdcf_idx'), models.Index(fields=['actor', 'created_at'], name='audit_logs__actor_i_36fd5e_idx')],
            },
        ),
    ]
