import {useEffect,useMemo,useState} from "react";
import {CheckCircle2,Clock3,FlaskConical,RefreshCw,Search,TestTube,X} from "lucide-react";
import Layout from "../../components/layout/Layout"; import api from "../../api/axios";
const fmt=v=>String(v||"").replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
export default function Laboratory(){
 const [rows,setRows]=useState([]),[search,setSearch]=useState(""),[status,setStatus]=useState("ALL"),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[form,setForm]=useState({});
 const load=async()=>{try{setError("");const r=await api.get("/laboratory/receptionist/");setRows(Array.isArray(r.data)?r.data:(r.data?.results||[]));}catch(e){setError(e.response?.data?.detail||"Unable to load lab requests.");}};
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>rows.filter(x=>(status==="ALL"||x.status===status)&&[x.patient_name,x.doctor_name,x.test_name,x.sample_id,x.priority].join(" ").toLowerCase().includes(search.toLowerCase())),[rows,search,status]);
 const open=x=>{setSelected(x);setForm({status:x.status,sample_id:x.sample_id||"",sample_type:x.sample_type||"",result_value:x.result_value||"",result_unit:x.result_unit||"",reference_range:x.reference_range||"",result_summary:x.result_summary||"",is_abnormal:!!x.is_abnormal,report_file:null});};
 const next=x=>x==="REQUESTED"?"SAMPLE_COLLECTED":x==="SAMPLE_COLLECTED"?"PROCESSING":x==="PROCESSING"?"COMPLETED":x;
 const save=async e=>{e.preventDefault();try{setBusy(true);const d=new FormData();Object.entries(form).forEach(([k,v])=>{if(k==="report_file"){if(v)d.append(k,v);}else d.append(k,v);});await api.patch(`/laboratory/receptionist/${selected.id}/`,d,{headers:{"Content-Type":"multipart/form-data"}});setSelected(null);await load();}catch(e){setError(e.response?.data?.detail||"Unable to update laboratory request.");}finally{setBusy(false);}};
 return <Layout><div className="page-content lab-workflow-page"><div className="page-header page-header-actions"><div><p className="page-eyebrow">RECEPTIONIST · LABORATORY</p><h1>Laboratory Workflow</h1><p className="page-description">Track sample collection, processing and laboratory result completion.</p></div><button className="btn-secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div>{error&&<div className="error-message">{error}</div>}
 <div className="lab-workflow-stats">{[["Total",rows.length,TestTube],["Requested",rows.filter(x=>x.status==="REQUESTED").length,Clock3],["Processing",rows.filter(x=>x.status==="PROCESSING").length,FlaskConical],["Completed",rows.filter(x=>x.status==="COMPLETED").length,CheckCircle2]].map(([a,b,I])=><div className="card lab-workflow-stat" key={a}><I size={20}/><div><strong>{b}</strong><span>{a}</span></div></div>)}</div>
 <div className="card lab-workflow-toolbar"><div className="search-box"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search patient, doctor, test or sample ID..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}>{["ALL","REQUESTED","SAMPLE_COLLECTED","PROCESSING","COMPLETED","CANCELLED"].map(x=><option value={x} key={x}>{fmt(x)}</option>)}</select></div>
 <div className="card"><div className="table-responsive"><table className="data-table"><thead><tr><th>Patient</th><th>Test</th><th>Doctor</th><th>Priority</th><th>Sample</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><strong>{x.patient_name}</strong></td><td>{x.test_name}</td><td>Dr. {x.doctor_name}</td><td><span className={`lab-priority lab-priority-${x.priority?.toLowerCase()}`}>{fmt(x.priority)}</span></td><td>{x.sample_id||"—"}</td><td><span className={`status-badge lab-status-${x.status?.toLowerCase()}`}>{fmt(x.status)}</span></td><td>{!["COMPLETED","CANCELLED"].includes(x.status)&&<button className="btn-small btn-primary" onClick={()=>open(x)}>Process</button>}</td></tr>)}</tbody></table></div></div>
 {selected&&<div className="modal-overlay"><div className="modal-card lab-workflow-modal"><button className="modal-close" onClick={()=>setSelected(null)}><X size={18}/></button><h2>{selected.test_name}</h2><p>{selected.patient_name} · Dr. {selected.doctor_name}</p><form onSubmit={save}><div className="form-group"><label>Next Status</label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value={selected.status}>{fmt(selected.status)}</option>{next(selected.status)!==selected.status&&<option value={next(selected.status)}>{fmt(next(selected.status))}</option>}<option value="CANCELLED">Cancelled</option></select></div>{selected.status==="REQUESTED"&&<><div className="form-group"><label>Sample ID</label><input value={form.sample_id} onChange={e=>setForm({...form,sample_id:e.target.value})} placeholder="Auto-generated if blank"/></div><div className="form-group"><label>Sample Type</label><input value={form.sample_type} onChange={e=>setForm({...form,sample_type:e.target.value})} placeholder="Blood, urine, serum..."/></div></>}{["PROCESSING","COMPLETED"].includes(form.status)&&<><div className="lab-result-fields"><div className="form-group"><label>Result Value</label><input value={form.result_value} onChange={e=>setForm({...form,result_value:e.target.value})}/></div><div className="form-group"><label>Unit</label><input value={form.result_unit} onChange={e=>setForm({...form,result_unit:e.target.value})}/></div></div><div className="form-group"><label>Reference Range</label><input value={form.reference_range} onChange={e=>setForm({...form,reference_range:e.target.value})}/></div><label className="lab-check"><input type="checkbox" checked={form.is_abnormal} onChange={e=>setForm({...form,is_abnormal:e.target.checked})}/> Mark result abnormal</label><div className="form-group"><label>Result Summary</label><textarea rows="4" value={form.result_summary} onChange={e=>setForm({...form,result_summary:e.target.value})}/></div><div className="form-group"><label>Report File</label><input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>setForm({...form,report_file:e.target.files?.[0]||null})}/></div></>}<button className="btn-primary" disabled={busy}>{busy?"Saving...":"Update Laboratory Request"}</button></form></div></div>}
 </div></Layout>;
}