# Generated by Django 6.0.3 on 2026-09-16 08:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='SmartCare Hospital', max_length=180)),
                ('hospital_registration_number', models.CharField(blank=True, max_length=100)),
                ('hospital_address', models.TextField(blank=True)),
                ('hospital_phone', models.CharField(blank=True, max_length=30)),
                ('hospital_email', models.EmailField(blank=True, max_length=254)),
                ('hospital_website', models.URLField(blank=True)),
                ('appointment_slot_minutes', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(240)])),
                ('advance_booking_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('cancellation_cutoff_hours', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(168)])),
                ('working_day_start', models.TimeField(default='09:00')),
                ('working_day_end', models.TimeField(default='18:00')),
                ('queue_enabled', models.BooleanField(default=True)),
                ('queue_token_prefix', models.CharField(default='T', max_length=10)),
                ('queue_start_number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('in_app_notifications_enabled', models.BooleanField(default=True)),
                ('appointment_reminders_enabled', models.BooleanField(default=True)),
                ('reminder_24h_enabled', models.BooleanField(default=True)),
                ('reminder_2h_enabled', models.BooleanField(default=True)),
                ('sms_notifications_enabled', models.BooleanField(default=False)),
                ('whatsapp_notifications_enabled', models.BooleanField(default=False)),
                ('lab_max_upload_mb', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('lab_allowed_file_types', models.CharField(default='pdf,jpg,jpeg,png', max_length=100)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee (INR)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)')], default='INR', max_length=3)),
                ('online_payments_enabled', models.BooleanField(default=True)),
                ('offline_payments_enabled', models.BooleanField(default=True)),
                ('hospital_timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.CharField(blank=True, default='SmartCare is temporarily under maintenance.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
