# Generated by Django 6.0.3 on 2026-09-15 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active_doctor_receptionist'),
        ('laboratory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='doctor_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='doctor_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='is_abnormal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='priority',
            field=models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'STAT')], default='ROUTINE', max_length=10),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='reference_range',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='result_unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='result_value',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='sample_collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='sample_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='sample_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='labtestrequest',
            index=models.Index(fields=['status', 'created_at'], name='laboratory__status_fde4c1_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestrequest',
            index=models.Index(fields=['patient', 'status'], name='laboratory__patient_944a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestrequest',
            index=models.Index(fields=['doctor', 'status'], name='laboratory__doctor__22c675_idx'),
        ),
    ]
