import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,CheckCircle2,Eye,FileText,FlaskConical,Plus,RefreshCw,Search,TestTube,X} from "lucide-react";
import Layout from "../../components/layout/Layout";
import api from "../../api/axios";
const fmt=v=>String(v||"").replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const results=r=>Array.isArray(r.data)?r.data:(r.data?.results||[]);
export default function LabReports(){
 const [patients,setPatients]=useState([]),[requests,setRequests]=useState([]),[search,setSearch]=useState(""),[status,setStatus]=useState("ALL"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[modal,setModal]=useState(false),[review,setReview]=useState(null),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const [form,setForm]=useState({patient:"",test_name:"",priority:"ROUTINE",instructions:""}),[notes,setNotes]=useState("");
 const load=async()=>{try{setLoading(true);setError("");const [p,r]=await Promise.all([api.get("/medical-records/doctor/patients/"),api.get("/laboratory/doctor/requests/")]);setPatients(results(p));setRequests(results(r));}catch(e){setError(e.response?.data?.detail||"Unable to load laboratory data.");}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>requests.filter(x=>(status==="ALL"||x.status===status)&&[x.patient_name,x.test_name,x.status,x.priority].join(" ").toLowerCase().includes(search.toLowerCase())),[requests,search,status]);
 const submit=async e=>{e.preventDefault();try{setBusy(true);await api.post("/laboratory/doctor/requests/",{...form,patient:Number(form.patient)});setModal(false);setSuccess("Laboratory test requested.");setForm({patient:"",test_name:"",priority:"ROUTINE",instructions:""});await load();}catch(e){setError(e.response?.data?.detail||"Unable to request test.");}finally{setBusy(false);}};
 const saveReview=async e=>{e.preventDefault();try{setBusy(true);await api.patch(`/laboratory/doctor/requests/${review.id}/`,{doctor_review_notes:notes});setReview(null);setSuccess("Result reviewed successfully.");await load();}catch(e){setError(e.response?.data?.detail||"Unable to save review.");}finally{setBusy(false);}};
 const completed=requests.filter(x=>x.status==="COMPLETED").length, abnormal=requests.filter(x=>x.is_abnormal).length;
 return <Layout><div className="page-content lab-workflow-page"><div className="page-header page-header-actions"><div><p className="page-eyebrow">DOCTOR · LABORATORY</p><h1>Lab Reports</h1><p className="page-description">Order tests, monitor sample progress and review completed laboratory results.</p></div><div className="lab-header-actions"><button className="btn-secondary" onClick={load}><RefreshCw size={16}/> Refresh</button><button className="btn-primary" onClick={()=>setModal(true)}><Plus size={17}/> Request Test</button></div></div>
 {error&&<div className="error-message">{error}</div>}{success&&<div className="success-message">{success}</div>}
 <div className="lab-workflow-stats">{[["Requests",requests.length,TestTube],["Completed",completed,CheckCircle2],["Abnormal",abnormal,AlertTriangle],["Patients",patients.length,FlaskConical]].map(([a,b,I])=><div className="card lab-workflow-stat" key={a}><I size={20}/><div><strong>{b}</strong><span>{a}</span></div></div>)}</div>
 <div className="card lab-workflow-toolbar"><div className="search-box"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search patient, test, priority or status..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}>{["ALL","REQUESTED","SAMPLE_COLLECTED","PROCESSING","COMPLETED","CANCELLED"].map(x=><option key={x} value={x}>{fmt(x)}</option>)}</select></div>
 <div className="card"><div className="table-responsive"><table className="data-table"><thead><tr><th>Patient</th><th>Test</th><th>Priority</th><th>Status</th><th>Result</th><th>Doctor Review</th><th>Action</th></tr></thead><tbody>{loading?<tr><td colSpan="7">Loading laboratory requests...</td></tr>:filtered.length?filtered.map(x=><tr key={x.id}><td><strong>{x.patient_name}</strong></td><td>{x.test_name}</td><td><span className={`lab-priority lab-priority-${x.priority?.toLowerCase()}`}>{fmt(x.priority)}</span></td><td><span className={`status-badge lab-status-${x.status?.toLowerCase()}`}>{fmt(x.status)}</span></td><td>{x.status==="COMPLETED"?<><strong>{x.result_value||"Result available"} {x.result_unit||""}</strong>{x.is_abnormal&&<span className="lab-abnormal-flag">Abnormal</span>}</>:"—"}</td><td>{x.doctor_reviewed_at?"Reviewed":"Pending"}</td><td>{x.status==="COMPLETED"&&<button className="btn-small btn-secondary" onClick={()=>{setReview(x);setNotes(x.doctor_review_notes||"");}}><Eye size={14}/> Review</button>}</td></tr>):<tr><td colSpan="7">No matching laboratory requests.</td></tr>}</tbody></table></div></div>
 {modal&&<div className="modal-overlay"><div className="modal-card lab-workflow-modal"><button className="modal-close" onClick={()=>setModal(false)}><X size={18}/></button><h2>Request Laboratory Test</h2><form onSubmit={submit}><div className="form-group"><label>Patient</label><select required value={form.patient} onChange={e=>setForm({...form,patient:e.target.value})}><option value="">Select patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="form-group"><label>Test Name</label><input required value={form.test_name} onChange={e=>setForm({...form,test_name:e.target.value})}/></div><div className="form-group"><label>Priority</label><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="ROUTINE">Routine</option><option value="URGENT">Urgent</option><option value="STAT">STAT</option></select></div><div className="form-group"><label>Instructions</label><textarea rows="4" value={form.instructions} onChange={e=>setForm({...form,instructions:e.target.value})}/></div><button className="btn-primary" disabled={busy}>{busy?"Requesting...":"Request Test"}</button></form></div></div>}
 {review&&<div className="modal-overlay"><div className="modal-card lab-workflow-modal"><button className="modal-close" onClick={()=>setReview(null)}><X size={18}/></button><h2>{review.test_name}</h2><div className={`lab-result-highlight ${review.is_abnormal?"abnormal":""}`}><strong>{review.result_value||"Result"} {review.result_unit||""}</strong><span>Reference: {review.reference_range||"Not specified"}</span></div><p>{review.result_summary}</p>{review.report_file_url&&<a className="btn-secondary" href={review.report_file_url} target="_blank" rel="noreferrer"><FileText size={15}/> Open Report</a>}<form onSubmit={saveReview}><div className="form-group"><label>Doctor Review Notes</label><textarea rows="4" value={notes} onChange={e=>setNotes(e.target.value)}/></div><button className="btn-primary" disabled={busy}>{busy?"Saving...":"Mark Reviewed"}</button></form></div></div>}
 </div></Layout>;
}