import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,CheckCircle2,Download,FlaskConical,RefreshCw,Search,TestTube} from "lucide-react";
import Layout from "../../components/layout/Layout"; import api from "../../api/axios";
const fmt=v=>String(v||"").replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
export default function LabReports(){
 const [rows,setRows]=useState([]),[search,setSearch]=useState(""),[status,setStatus]=useState("ALL"),[error,setError]=useState("");
 const load=async()=>{try{setError("");const r=await api.get("/laboratory/patient/");setRows(Array.isArray(r.data)?r.data:(r.data?.results||[]));}catch(e){setError(e.response?.data?.detail||"Unable to load lab reports.");}};
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>rows.filter(x=>(status==="ALL"||x.status===status)&&[x.test_name,x.doctor_name,x.result_summary,x.status].join(" ").toLowerCase().includes(search.toLowerCase())),[rows,search,status]);
 return <Layout><div className="page-content lab-workflow-page patient-lab-upgrade"><div className="page-header page-header-actions"><div><p className="page-eyebrow">PATIENT · LABORATORY</p><h1>Lab Reports</h1><p className="page-description">Track your samples and securely review completed laboratory results.</p></div><button className="btn-secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div>{error&&<div className="error-message">{error}</div>}
 <div className="lab-workflow-stats">{[["Tests",rows.length,TestTube],["Completed",rows.filter(x=>x.status==="COMPLETED").length,CheckCircle2],["Processing",rows.filter(x=>["SAMPLE_COLLECTED","PROCESSING"].includes(x.status)).length,FlaskConical],["Abnormal",rows.filter(x=>x.is_abnormal).length,AlertTriangle]].map(([a,b,I])=><div className="card lab-workflow-stat" key={a}><I size={20}/><div><strong>{b}</strong><span>{a}</span></div></div>)}</div>
 <div className="card lab-workflow-toolbar"><div className="search-box"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search test, doctor, result or status..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}>{["ALL","REQUESTED","SAMPLE_COLLECTED","PROCESSING","COMPLETED","CANCELLED"].map(x=><option key={x} value={x}>{fmt(x)}</option>)}</select></div>
 <div className="patient-lab-upgrade-grid">{filtered.map(x=><article className={`card patient-lab-upgrade-card ${x.is_abnormal?"has-abnormal":""}`} key={x.id}><div className="patient-lab-upgrade-head"><div><span className={`lab-priority lab-priority-${x.priority?.toLowerCase()}`}>{fmt(x.priority)}</span><h3>{x.test_name}</h3><p>Dr. {x.doctor_name}</p></div><span className={`status-badge lab-status-${x.status?.toLowerCase()}`}>{fmt(x.status)}</span></div><div className="lab-progress"><span className={x.status!=="REQUESTED"?"done":""}>Requested</span><span className={["SAMPLE_COLLECTED","PROCESSING","COMPLETED"].includes(x.status)?"done":""}>Sample</span><span className={["PROCESSING","COMPLETED"].includes(x.status)?"done":""}>Processing</span><span className={x.status==="COMPLETED"?"done":""}>Result</span></div>{x.sample_id&&<p className="lab-sample-line">Sample ID: <strong>{x.sample_id}</strong> · {x.sample_type||"Sample"}</p>}{x.status==="COMPLETED"&&<div className={`lab-result-highlight ${x.is_abnormal?"abnormal":""}`}><strong>{x.result_value||"Result available"} {x.result_unit||""}</strong><span>Reference: {x.reference_range||"Not specified"}</span><p>{x.result_summary}</p>{x.is_abnormal&&<b><AlertTriangle size={14}/> Abnormal result — discuss with your doctor</b>}</div>}<div className="patient-lab-upgrade-foot"><span>{x.doctor_reviewed_at?"Reviewed by doctor":"Awaiting doctor review"}</span>{x.report_file_url&&<a href={x.report_file_url} target="_blank" rel="noreferrer" className="btn-secondary"><Download size={15}/> Report</a>}</div></article>)}</div>
 </div></Layout>;
}