import {Activity,BellRing,Building2,CalendarDays,CheckCircle2,Clock3,CreditCard,FlaskConical,LoaderCircle,Save,Settings2,ShieldCheck,TicketCheck} from "lucide-react";
import {useCallback,useEffect,useMemo,useState} from "react";
import api from "../../api/axios";
import Layout from "../../components/layout/Layout";

const defaults={hospital_name:"",hospital_registration_number:"",hospital_address:"",hospital_phone:"",hospital_email:"",hospital_website:"",appointment_slot_minutes:30,advance_booking_days:30,cancellation_cutoff_hours:2,working_day_start:"09:00",working_day_end:"18:00",queue_enabled:true,queue_token_prefix:"T",queue_start_number:1,in_app_notifications_enabled:true,appointment_reminders_enabled:true,reminder_24h_enabled:true,reminder_2h_enabled:true,sms_notifications_enabled:false,whatsapp_notifications_enabled:false,lab_max_upload_mb:10,lab_allowed_file_types:"pdf,jpg,jpeg,png",currency:"INR",online_payments_enabled:true,offline_payments_enabled:true,hospital_timezone:"Asia/Kolkata",session_timeout_minutes:10,maintenance_mode:false,maintenance_message:""};

function Toggle({label,description,checked,onChange,disabled=false}){return <label className={`system-setting-toggle ${disabled?"is-disabled":""}`}><span><strong>{label}</strong>{description&&<small>{description}</small>}</span><span className="system-setting-switch"><input type="checkbox" checked={!!checked} onChange={e=>onChange(e.target.checked)} disabled={disabled}/><span className="system-setting-switch-track"/></span></label>}
function Section({icon:Icon,title,description,children}){return <section className="card system-settings-card"><div className="system-settings-card-header"><div className="system-settings-card-icon"><Icon size={20}/></div><div><h2>{title}</h2><p>{description}</p></div></div><div className="system-settings-card-body">{children}</div></section>}
function Field({label,name,type="text",form,update,min,max,placeholder,full=false}){return <label className={`system-setting-field ${full?"full-width":""}`}><span>{label}</span><input type={type} min={min} max={max} placeholder={placeholder} value={form[name]??""} onChange={e=>update(name,e.target.value)}/></label>}

function SystemSettings(){
 const [form,setForm]=useState(defaults),[original,setOriginal]=useState(defaults),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState(""),[meta,setMeta]=useState({});
 const dirty=useMemo(()=>JSON.stringify(form)!==JSON.stringify(original),[form,original]);
 const update=(n,v)=>{setForm(x=>({...x,[n]:v}));setSuccess("")};
 const load=useCallback(async()=>{try{setLoading(true);setError("");const {data}=await api.get("/system-settings/admin/");const x={...defaults,...data,working_day_start:data.working_day_start?.slice(0,5)||"09:00",working_day_end:data.working_day_end?.slice(0,5)||"18:00"};setForm(x);setOriginal(x);setMeta(data)}catch(e){setError(e.response?.data?.detail||"Unable to load system settings.")}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const save=async()=>{try{setSaving(true);setError("");const payload={...form,appointment_slot_minutes:Number(form.appointment_slot_minutes),advance_booking_days:Number(form.advance_booking_days),cancellation_cutoff_hours:Number(form.cancellation_cutoff_hours),queue_start_number:Number(form.queue_start_number),lab_max_upload_mb:Number(form.lab_max_upload_mb),session_timeout_minutes:Number(form.session_timeout_minutes)};const {data}=await api.patch("/system-settings/admin/",payload);const x={...defaults,...data,working_day_start:data.working_day_start?.slice(0,5),working_day_end:data.working_day_end?.slice(0,5)};setForm(x);setOriginal(x);setMeta(data);setSuccess("System settings saved successfully.")}catch(e){const d=e.response?.data;setError(d&&typeof d==="object"?JSON.stringify(d):"Unable to save system settings.")}finally{setSaving(false)}};
 if(loading)return <Layout><div className="loading-screen"><LoaderCircle className="spin" size={24}/> Loading system settings...</div></Layout>;
 return <Layout><div className="page-content system-settings-page">
  <div className="page-header page-header-actions"><div><p className="page-eyebrow">ADMINISTRATION</p><h1>System Settings</h1><p className="page-description">Configure hospital operations without exposing payment, SMS or WhatsApp secrets.</p></div><div className="system-settings-header-actions">{dirty&&<button className="btn-secondary" onClick={()=>setForm(original)}>Reset</button>}<button className="btn-primary" disabled={saving||!dirty} onClick={save}>{saving?<LoaderCircle className="spin" size={17}/>:<Save size={17}/>} {saving?"Saving...":"Save Changes"}</button></div></div>
  {error&&<div className="error-message system-settings-alert">{error}</div>}{success&&<div className="system-settings-success"><CheckCircle2 size={18}/>{success}</div>}
  <div className="system-settings-summary"><div><Settings2 size={19}/><span><strong>Configuration</strong><small>{dirty?"Unsaved changes":"All changes saved"}</small></span></div><div><ShieldCheck size={19}/><span><strong>Admin protected</strong><small>Only ADMIN users can update</small></span></div><div><Activity size={19}/><span><strong>Last updated</strong><small>{meta.updated_at?new Date(meta.updated_at).toLocaleString():"Not updated yet"} {meta.updated_by_name?`by ${meta.updated_by_name}`:""}</small></span></div></div>
  <div className="system-settings-grid">
   <Section icon={Building2} title="Hospital Profile" description="Hospital identity and contact information."><div className="system-settings-fields two-columns"><Field label="Hospital name" name="hospital_name" form={form} update={update}/><Field label="Registration number" name="hospital_registration_number" form={form} update={update}/><Field label="Phone" name="hospital_phone" form={form} update={update}/><Field label="Email" name="hospital_email" type="email" form={form} update={update}/><Field label="Website" name="hospital_website" type="url" form={form} update={update} full/><label className="system-setting-field full-width"><span>Address</span><textarea rows="3" value={form.hospital_address} onChange={e=>update("hospital_address",e.target.value)}/></label></div></Section>
   <Section icon={CalendarDays} title="Appointments" description="Booking windows, slot duration and hospital hours."><div className="system-settings-fields two-columns"><Field label="Slot duration (minutes)" name="appointment_slot_minutes" type="number" min="5" max="240" form={form} update={update}/><Field label="Advance booking (days)" name="advance_booking_days" type="number" min="1" max="365" form={form} update={update}/><Field label="Cancellation cutoff (hours)" name="cancellation_cutoff_hours" type="number" min="0" max="168" form={form} update={update}/><Field label="Timezone" name="hospital_timezone" form={form} update={update}/><Field label="Working day starts" name="working_day_start" type="time" form={form} update={update}/><Field label="Working day ends" name="working_day_end" type="time" form={form} update={update}/></div></Section>
   <Section icon={TicketCheck} title="Live Queue" description="Token generation preferences."><Toggle label="Enable live queue" checked={form.queue_enabled} onChange={v=>update("queue_enabled",v)}/><div className="system-settings-fields two-columns compact-top"><Field label="Token prefix" name="queue_token_prefix" form={form} update={update}/><Field label="Starting token number" name="queue_start_number" type="number" min="1" max="9999" form={form} update={update}/></div></Section>
   <Section icon={BellRing} title="Notifications & Reminders" description="Operational notification channels."><div className="system-settings-toggle-list"><Toggle label="In-app notifications" checked={form.in_app_notifications_enabled} onChange={v=>update("in_app_notifications_enabled",v)}/><Toggle label="Appointment reminders" checked={form.appointment_reminders_enabled} onChange={v=>update("appointment_reminders_enabled",v)}/><Toggle label="24-hour reminder" disabled={!form.appointment_reminders_enabled} checked={form.reminder_24h_enabled} onChange={v=>update("reminder_24h_enabled",v)}/><Toggle label="2-hour reminder" disabled={!form.appointment_reminders_enabled} checked={form.reminder_2h_enabled} onChange={v=>update("reminder_2h_enabled",v)}/><Toggle label="SMS notifications" description="Requires backend provider credentials." checked={form.sms_notifications_enabled} onChange={v=>update("sms_notifications_enabled",v)}/><Toggle label="WhatsApp notifications" description="Requires backend provider credentials." checked={form.whatsapp_notifications_enabled} onChange={v=>update("whatsapp_notifications_enabled",v)}/></div></Section>
   <Section icon={FlaskConical} title="Laboratory" description="Safe report-upload limits."><div className="system-settings-fields two-columns"><Field label="Maximum report size (MB)" name="lab_max_upload_mb" type="number" min="1" max="50" form={form} update={update}/><Field label="Allowed types" name="lab_allowed_file_types" form={form} update={update}/></div></Section>
   <Section icon={CreditCard} title="Billing & Payments" description="Payment controls without exposing secrets."><label className="system-setting-field"><span>Currency</span><select value={form.currency} onChange={e=>update("currency",e.target.value)}><option value="INR">INR — Indian Rupee</option><option value="USD">USD</option><option value="EUR">EUR</option><option value="GBP">GBP</option></select></label><div className="system-settings-toggle-list compact-top"><Toggle label="Online payments" checked={form.online_payments_enabled} onChange={v=>update("online_payments_enabled",v)}/><Toggle label="Offline payments" checked={form.offline_payments_enabled} onChange={v=>update("offline_payments_enabled",v)}/></div></Section>
   <Section icon={Clock3} title="Security & Session" description="Operational session preferences."><Field label="Session timeout (minutes)" name="session_timeout_minutes" type="number" min="5" max="1440" form={form} update={update}/></Section>
   <Section icon={Settings2} title="Maintenance" description="Public maintenance state and message."><Toggle label="Maintenance mode" checked={form.maintenance_mode} onChange={v=>update("maintenance_mode",v)}/><label className="system-setting-field compact-top"><span>Maintenance message</span><textarea rows="3" value={form.maintenance_message} onChange={e=>update("maintenance_message",e.target.value)} disabled={!form.maintenance_mode}/></label></Section>
  </div>
 </div></Layout>
}
export default SystemSettings;
