# Generated by Django 6.0.3 on 2026-09-14 18:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_is_active_doctor_receptionist'),
        ('appointments', '0003_appointment_appointment_appoint_c5b816_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('token_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('IN_SERVICE', 'In Consultation'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], db_index=True, default='WAITING', max_length=30)),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('service_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_ticket', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_queue_tickets', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_tickets', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['queue_date', 'doctor_id', 'token_number'],
                'indexes': [models.Index(fields=['doctor', 'queue_date', 'status'], name='queue_doc_date_status_idx'), models.Index(fields=['patient', 'queue_date'], name='queue_patient_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'queue_date', 'token_number'), name='unique_doctor_daily_queue_token')],
            },
        ),
    ]
