# Generated by Django 6.0.3 on 2026-09-15 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_appointment_appointment_appoint_c5b816_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('24H', '24 Hours Before'), ('2H', '2 Hours Before')], max_length=10)),
                ('in_app_sent', models.BooleanField(default=False)),
                ('external_sent', models.BooleanField(default=False)),
                ('external_channel_attempted', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reminder_type', 'sent_at'], name='appt_rem_type_sent_idx'), models.Index(fields=['appointment', 'reminder_type'], name='appt_rem_appt_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('appointment', 'reminder_type'), name='unique_appointment_reminder_type')],
            },
        ),
    ]
